version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./Capnp.Net.Runtime/Capnp.Net.Runtime.csproj --verbosity m
  - cmd: dotnet restore ./capnpc-csharp/capnpc-csharp.csproj --verbosity m
build_script:
  - cmd: dotnet publish -c Release -r win-x86 --self-contained -o bin\win_x86 ./capnpc-csharp/capnpc-csharp.csproj
after_build:
  # For once the build has completed
artifacts:
 - path: 'bin\win_x86'
   name: WebSite
   type: WebDeployPackage
clone_depth: 1
test_script:
  # restore packages for our unit tests
  - cmd: dotnet restore ./Capnp.Net.Runtime.Tests.Core21/Capnp.Net.Runtime.Tests.Core21.csproj --verbosity m
  - cmd: msbuild ./CapnpCompatTest.sln
  - cmd: cd Capnp.Net.Runtime.Tests.Core21
  - cmd: dotnet test
on_finish :
  # any cleanup in here
deploy: off