version: '1.0.{build}'
image: Visual Studio 2019
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  - cd c:\tools\vcpkg
  - vcpkg integrate install
  - vcpkg install capnproto
  - cd %APPVEYOR_BUILD_FOLDER%
before_build:
  - cmd: dotnet --version
  - cmd: msbuild -ver
  - cmd: dotnet restore ./Capnp.Net.Runtime/Capnp.Net.Runtime.csproj --verbosity m
  - cmd: dotnet restore ./Capnp.Net.Runtime.Core21/Capnp.Net.Runtime.Core21.csproj --verbosity m
  - cmd: dotnet restore ./Capnp.Net.Runtime.Tests/Capnp.Net.Runtime.Tests.Std20.csproj --verbosity m
  - cmd: dotnet restore ./Capnp.Net.Runtime.Tests.Core21/Capnp.Net.Runtime.Tests.Core21.csproj --verbosity m
  - cmd: dotnet restore ./capnpc-csharp/capnpc-csharp.csproj --verbosity m  
build_script:
  - cmd: msbuild ./Capnp.Net.sln /p:Configuration="Debug"
  - cmd: msbuild ./Capnp.Net.sln /p:Configuration="Release"
  - cmd: msbuild ./CapnpCompatTest.sln /p:Configuration="Debug"
  - cmd: msbuild ./CapnpCompatTest.sln /p:Configuration="Release"
  - cmd: scripts\capnpc-csharp-pack.ps1
after_build:
  # For once the build has completed
artifacts:
 - path: Capnp.Net.Runtime\bin\Debug\Capnp.Net.Runtime.1.0.0.nupkg
   name: Capnp.Net.Runtime.1.0.0_debug
   type: NuGetPackage
 - path: Capnp.Net.Runtime\bin\Release\Capnp.Net.Runtime.1.0.0.nupkg
   name: Capnp.Net.Runtime.1.0.0
   type: NuGetPackage
 - path: chocolatey\install\capnpc-csharp-win-x86.1.0.0.nupkg
   name: capnpc-csharp-win-x86.1.0.0
   type: NuGetPackage
 - path: chocolatey\install\capnpc-csharp.1.0.0.nupkg
   name: capnpc-csharp.1.0.0
   type: NuGetPackage
clone_depth: 1
test_script:
  - cmd: vstest.console /logger:Appveyor /inIsolation Capnp.Net.Runtime.Tests\bin\Debug\netcoreapp2.2\Capnp.Net.Runtime.Tests.Std20.dll
  - cmd: vstest.console /logger:Appveyor /inIsolation Capnp.Net.Runtime.Tests\bin\Release\netcoreapp2.2\Capnp.Net.Runtime.Tests.Std20.dll
  - cmd: vstest.console /logger:Appveyor /inIsolation Capnp.Net.Runtime.Tests.Core21\bin\Debug\netcoreapp2.2\Capnp.Net.Runtime.Tests.Core21.dll
  - cmd: vstest.console /logger:Appveyor /inIsolation Capnp.Net.Runtime.Tests.Core21\bin\Release\netcoreapp2.2\Capnp.Net.Runtime.Tests.Core21.dll
on_finish :
  # any cleanup in here
deploy: off